version: 1
update_configs:
  - package_manager: "submodules"
    directory: "./"
    update_schedule: "daily"
    allowed_updates:
      - match:
          dependency_name: "1-fertmanasa"
      - match:
          dependency_name: "1-qsqnk"
      - match:
          dependency_name: "1-IraSheremet"
      - match:
          dependency_name: "1-smmac72"
      - match:
          dependency_name: "1-ShishaK1N9"
      - match:
          dependency_name: "1-pervomai"
      - match:
          dependency_name: "1-IAmFunkyFrog"
      - match:
          dependency_name: "1-Mishavint"
      - match:
          dependency_name: "1-MDubovik"
      - match:
          dependency_name: "1-PyRayman"
      - match:
          dependency_name: "1-artmotika"
      - match:
          dependency_name: "1-AzimMuradov"
      - match:
          dependency_name: "1-Naniduan"
      - match:
          dependency_name: "1-Lev0nid"
      - match:
          dependency_name: "1-MansurSakiev"
      - match:
          dependency_name: "1-michael555444"
      - match:
          dependency_name: "1-DelRoso"
      - match:
          dependency_name: "1-SofuriHafe"
      - match:
          dependency_name: "1-foreverjun"
      - match:
          dependency_name: "1-esvault"
      - match:
          dependency_name: "1-TheDarkRisen"
      - match:
          dependency_name: "1-TimPushkin"
      - match:
          dependency_name: "1-ToTTopBYxe"
      - match:
          dependency_name: "1-kettlberry"
      - match:
          dependency_name: "1-danielsheh02"
      - match:
          dependency_name: "1-zishkaz"
      - match:
          dependency_name: "1-Ramazanov-Amir"
      - match:
          dependency_name: "1-MashrurIslam"
      - match:
          dependency_name: "1-rudolf101"
    ignored_updates:
      - match:
          dependency_name: "1-grading-tests"
